module GestAcces {
	typedef string Photo;
	typedef short Heure;

	struct Jour {
	    short annee;
	    short mois;
	    short jour;
	};


    struct Date {
        Jour j;
        Heure h;
        short m;
    };

	struct Zone {
	    short idZone;
	    string nomZone;
	    string tailleZone;
	    string typeZone;
	};


	struct Log {
	    Date date;
	    string log;
	};

	struct Empreinte {
	    string empreinte;
	    short idCollaborateur;
	};

	struct Collaborateur {
            string nom;
            string prenom;
            string adresse;
            string statut;
            string login;
            string mdp;
            Photo photo;
            short dateEntree;
            Empreinte e;
    	};


	interface ServeurAnnuaire {
		exception CollaborateurInnexistant {};
		exception CollaborateurDejaExistant {};

		void enregisterCollaborateur(in string nom, in string prenom, in Photo p) raises(CollaborateurDejaExistant);
		void rechercherCollaborateur(in string nom, in string prenom);
		void supprimerCollaborateur(in short id) raises(CollaborateurInnexistant);
	};


	interface ServeurEmpreinte {
		exception EmpreinteInexistante {};
		exception EmpreintePresente{};
		exception EmpreinteInvalide{};

		void enregistrerEmpreinte(in Empreinte e) raises(EmpreintePresente);
		void modifierEmpreinte(in short idCollaborateur, in string nouvelleEmpreinte) raises (EmpreinteInexistante);
		void supprimerEmpreinte(in short idCollaborateur) raises (EmpreinteInexistante);
		void verifierEmpreinte(in short idCollaborateur,in string mdp) raises (EmpreinteInvalide);
	};

    typedef sequence<Log> lLog;

	interface ServeurLog {
		oneway void envoyerLog(in string log);
		oneway lLog afficherLogs();
		oneway lLog afficherLogsFromDate(in Date date);
		oneway lLog afficherLogsfromDateToDate(in Date dated, in Date datef);

	};

	typedef sequence<Zone> lZone;

	interface ServeurAcces {
		exception CollaborateurDejaExistant {};
		exception CollaborateurInexistant {};
		exception ZoneInexistante {};

		short ajoutPerm(in short id, in Heure heureDebut, in Heure heureFin, in Zone z) raises (ZoneInexistante);
		short ajoutTemp(in short id, in Jour jourDeb, in Jour jourFin,in Heure heureDebut, in Heure heureFin, in Zone z) raises (ZoneInexistante);
		short demanderAcces(in string Photo, in string mdp);
		void supprimerAcces (in short idCollaborateur, in short idZone) raises (CollaborateurInexistant);
		short verifierAcces (in short idCollaborateur,in short idZone);
		lZone getListeZone();

	};
};